"""Package the BalanceBench sources in the dedicated WC3 demo map."""
from pathlib import Path
import argparse
import os
import shutil
import struct
import subprocess

ROOT = Path(__file__).resolve().parents[1]
MAP = ROOT / "Map" / "BalanceBenchDemo.w3x"
SOURCE_MAP = ROOT / "Map" / "BalanceBenchBase.w3m"
INFO = ROOT / "Map" / "BalanceBenchInfo.w3i"
BUILD = ROOT / "Build" / "map"
TRIGGERS = ROOT / "Map" / "BalanceBenchTriggers.wtg"
TRIGGER_METADATA = ROOT / "Map" / "BalanceBenchTriggers.w3l"

parser = argparse.ArgumentParser()
parser.add_argument("--rounds", type=int)
parser.add_argument("--timeout", type=int)
parser.add_argument("--team-a-count", type=int)
parser.add_argument("--team-a-rawcode")
parser.add_argument("--team-b-count", type=int)
parser.add_argument("--team-b-rawcode")
parser.add_argument("--label")
parser.add_argument("--scenario")
parser.add_argument("--source-map", type=Path, default=SOURCE_MAP)
parser.add_argument("--output", type=Path, default=MAP)
parser.add_argument("--mpq-editor", type=Path,
                    help="Path to MPQEditor.exe (or set WC3_MPQ_EDITOR)")
args = parser.parse_args()

mpq_editor_value = args.mpq_editor or os.environ.get("WC3_MPQ_EDITOR") or shutil.which("MPQEditor.exe")
if not mpq_editor_value:
    parser.error("MPQEditor.exe not found; pass --mpq-editor or set WC3_MPQ_EDITOR")
mpq_editor = Path(mpq_editor_value)
if not mpq_editor.is_file():
    parser.error(f"MPQEditor.exe not found: {mpq_editor}")

source_map = args.source_map if args.source_map.is_absolute() else ROOT / args.source_map
output_map = args.output if args.output.is_absolute() else ROOT / args.output
assert source_map.is_file(), f"Source map missing: {source_map}"
output_map.parent.mkdir(parents=True, exist_ok=True)

BUILD.mkdir(parents=True, exist_ok=True)
info = INFO.read_bytes()
# WC3 3.0's format-39 map info: script language and player count offsets.
assert struct.unpack_from("<I", info, 0)[0] == 39
assert struct.unpack_from("<I", info, 0xD3)[0] == 1, "Lua map expected"
assert struct.unpack_from("<I", info, 0x113)[0] == 2, "two players expected"

runner = (ROOT / "Scripts" / "BalanceBench.lua").read_text(encoding="utf-8")
config = (ROOT / "Scripts" / "ExampleConfig.lua").read_text(encoding="utf-8")
if args.rounds is not None:
    assert args.rounds > 0 and args.rounds % 2 == 0
    config = config.replace("rounds = 20,", f"rounds = {args.rounds},")
if args.timeout is not None:
    assert 1 <= args.timeout <= 600
    config = config.replace("timeoutSeconds = 60,", f"timeoutSeconds = {args.timeout},")
if args.team_a_count is not None:
    assert 1 <= args.team_a_count <= 24
    config = config.replace('teamA = { rawcode = "hfoo", count = 3 },',
                            f'teamA = {{ rawcode = "hfoo", count = {args.team_a_count} }},')
if args.team_a_rawcode is not None:
    assert len(args.team_a_rawcode) == 4 and args.team_a_rawcode.isascii()
    config = config.replace('teamA = { rawcode = "hfoo",',
                            f'teamA = {{ rawcode = "{args.team_a_rawcode}",')
if args.team_b_count is not None:
    assert 1 <= args.team_b_count <= 24
    config = config.replace('teamB = { rawcode = "ogru", count = 2 },',
                            f'teamB = {{ rawcode = "ogru", count = {args.team_b_count} }},')
if args.team_b_rawcode is not None:
    assert len(args.team_b_rawcode) == 4 and args.team_b_rawcode.isascii()
    config = config.replace('teamB = { rawcode = "ogru",',
                            f'teamB = {{ rawcode = "{args.team_b_rawcode}",')
if args.label is not None:
    assert args.label and '"' not in args.label and "\n" not in args.label
    config = config.replace('label = "baseline",', f'label = "{args.label}",')
if args.scenario is not None:
    assert args.scenario and '"' not in args.scenario and "\n" not in args.scenario
    config = config.replace('scenario = "footmen-vs-grunts",',
                            f'scenario = "{args.scenario}",')
script = "\n".join([
    "-- Generated by Tools/build_demo.py from editable project sources.",
    runner,
    config,
    r'''
function config()
    SetMapName("Balance Bench Demo")
    SetMapDescription("Two-player sandbox for BalanceBench")
    SetPlayers(2)
    SetTeams(2)
    SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)
    DefineStartLocation(0, 1984.0, 1472.0)
    DefineStartLocation(1, -1984.0, -1472.0)
    SetPlayerStartLocation(Player(0), 0)
    SetPlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRacePreference(Player(1), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(0), true)
    SetPlayerRaceSelectable(Player(1), true)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerController(Player(1), MAP_CONTROL_COMPUTER)
    SetPlayerSlotAvailable(Player(0), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(1), MAP_CONTROL_COMPUTER)
    InitGenericPlayerSlots()
end

function main()
    SetCameraBounds(-3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT),
        -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM),
        3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT),
        3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP),
        -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT),
        3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP),
        3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT),
        -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl",
        "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    InitBlizzard()
    BalanceBenchDemoSetup()
end
''',
])
(BUILD / "war3map.lua").write_text(script, encoding="utf-8", newline="\r\n")
(BUILD / "war3map.w3i").write_bytes(info)

# Keep the same source in World Editor's map-header custom text. Without WCT,
# saving the map regenerates war3map.lua and silently discards BalanceBench.
editor_source = (runner + "\n" + config).replace("\n", "\r\n").encode("utf-8")
assert b"\0" not in editor_source
header_help = (
    b"Enter map-specific custom script code below.  This text will be included "
    b"in the map script after variables are declared and before any trigger code "
    b"except Custom Script Item. Custom Script Item will merge into map script "
    b"after globals variables declaration with the list order in trigger view.\0"
)
editor_text = (
    struct.pack("<II", 0x80000004, 1) + header_help
    + struct.pack("<I", len(editor_source) + 1) + editor_source + b"\0"
    + struct.pack("<II", 0, 0)
)
(BUILD / "war3map.wct").write_bytes(editor_text)

assert source_map.resolve() != output_map.resolve(), "Source and output map must differ"
shutil.copy2(source_map, output_map)
commands = "\n".join([
    f'add "{output_map}" "{BUILD / "war3map.w3i"}" "war3map.w3i" /auto',
    f'add "{output_map}" "{TRIGGERS}" "war3map.wtg" /auto',
    f'add "{output_map}" "{TRIGGER_METADATA}" "war3map.w3l" /auto',
    f'add "{output_map}" "{BUILD / "war3map.wct"}" "war3map.wct" /auto',
    f'add "{output_map}" "{BUILD / "war3map.lua"}" "war3map.lua" /auto',
    "close",
])
command_file = BUILD / "package_mpq.txt"
command_file.write_text(commands + "\n", encoding="ascii")
subprocess.run([str(mpq_editor), "/console", str(command_file)], check=True)
print(f"Packaged {output_map} ({output_map.stat().st_size} bytes)")
